name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install automake
      run: sudo apt-get install automake
    - name: autotools
      working-directory: ./openmp
      run: |
        autoreconf --install
        autoconf
        automake --add-missing
    - name: configure
      working-directory: ./openmp
      run: ./configure
    - name: make
      working-directory: ./openmp
      run: make
    - name: make check
      working-directory: ./openmp
      run: make check
    - name: make distcheck
      working-directory: ./openmp
      run: make distcheck
